export const api_get_block = `https://api.fantom.network/api/v1/get-blocks`;
export const api_get_transactions = `https://api.fantom.network/api/v1/get-transactions`;
export const api_get_price = `https://ec2-18-216-196-200.us-east-2.compute.amazonaws.com:3000/api/get-price`;
export const api_get_validators = `https://api.fantom.network/api/v1/staker/?verbosity=2`;
export const api_get_epoch = `https://api.fantom.network/api/v1/epoch/latest`;
export const api_get_singleTransaction = `https://api.fantom.network/api/v1/get-transaction?transactionHash=`;
export const api_get_singleValidators = `https://api.fantom.network/api/v1/staker/id/`;
export const api_get_singleValidatorsDelegator = `https://api.fantom.network/api/v1/delegator/staker/`;
export const api_get_address = `https://api.fantom.network/api/v1/get-account?address=`;
