export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_REALTIME_UPDATE = 'SET_REALTIME_UPDATE';
export const SET_BLOCK_DATA = 'SET_BLOCK_DATA';

export const SET_LATEST_BLOCK_DATA = 'SET_LATEST_BLOCK_DATA';
export const GET_LATEST_BLOCK_DATA = 'GET_LATEST_BLOCK_DATA';
