// @flow

export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_REALTIME_UPDATE = 'SET_REALTIME_UPDATE';
export const SET_BLOCK_DATA = 'SET_BLOCK_DATA';

export const SET_LATEST_BLOCKS_DATA = 'SET_LATEST_BLOCKS_DATA';
export const GET_LATEST_BLOCKS_DATA = 'GET_LATEST_BLOCKS_DATA';
export const LOADING_LATEST_BLOCKS_DATA = 'LOADING_LATEST_BLOCKS_DATA';
