// @flow

export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_REALTIME_UPDATE = 'SET_REALTIME_UPDATE';
export const SET_BLOCK_DATA = 'SET_BLOCK_DATA';

export const SET_LATEST_BLOCKS_DATA = 'SET_LATEST_BLOCKS_DATA';
export const GET_LATEST_BLOCKS_DATA = 'GET_LATEST_BLOCKS_DATA';
export const LOADING_LATEST_BLOCKS_DATA = 'LOADING_LATEST_BLOCKS_DATA';
export const UPDATE_LATEST_BLOCKS_DATA = 'UPDATE_LATEST_BLOCKS_DATA';

export const SUBSCRIBE_TO_NEW_BLOCKS = 'SUBSCRIBE_TO_NEW_BLOCKS';
export const UNSUBSCRIBE_TO_NEW_BLOCKS = 'UNSUBSCRIBE_TO_NEW_BLOCKS';

export const REQUEST_BLOCK_DATA = 'REQUEST_BLOCK_DATA';
